fixes missing currentAudio function
HE-Arc/pwa-playlist-generator pull request #18
Opened 2021-10-27 05:11 UTC by DevAshleyD

2021-10-27 05:12 UTC, DevAshleyD commented
works!

2021-10-27 05:13 UTC, DevAshleyD commented
works!

2021-10-31 10:16 UTC, qtipee requested changes

2021-10-31 10:16 UTC, qtipee commented on js/common.js
> +};
I do not understand what is the purpose of this code section ; could you explain please?

2021-10-31 10:16 UTC, qtipee commented on js/common.js
> +function filenameWithoutPath(filename, ext = false) {
I also prefer the K&R style for JS today, but this would break the consistency with the other files ; please also update the other files if you have a tool for that or leave the Allman style and I'll open an issue for that :)

2024-01-13 07:46 UTC, closed without merging